#48 allow to set a directory target without filename.
wp-cli/dist-archive-command pull request #49
Opened 2022-02-20 20:33 UTC by janw-me

2022-02-20 20:34 UTC, janw-me commented
Will try to add behat fucntional tests but wp-cli-dev is giving [problems](https://github.com/wp-cli/wp-cli-dev/issues/23)

2022-03-10 15:52 UTC, schlessera requested changes

2022-03-10 15:52 UTC, schlessera commented on README.md
> +		Path and optional file name for the distribution archive. If only a path is provided the file name defaults to project directory name plus version, if discoverable.
```suggestion
		Path and optional file name for the distribution archive. If only a path is provided, the file name defaults to the project directory name plus the version, if discoverable.
```

2022-03-10 16:14 UTC, merged

2022-06-04 01:23 UTC, BrianHenryIE commented
Brill. I needed this feature too, thank you. Tests in #56 cover this.