Fix #57 Check is there a symlink in the plugin; copy non-ignored files to temp
wp-cli/dist-archive-command pull request #59
Opened 2022-06-03 01:44 UTC by BrianHenryIE

Needs tests.

2022-06-30 17:04 UTC, schlessera requested changes
Code looks,

2022-06-30 17:04 UTC, schlessera commented on features/dist-archive.feature
> +      wordpress
The tests should trigger the extra regex rules as well to ensure they work as expected:
- using an asterisk
- using a slash
- using a dot

2022-07-01 05:44 UTC, BrianHenryIE commented on src/Dist_Archive_Command.php
> +			 */
This was needed in PhpStorm. It was not auto-completing the `$item` class without it.

2022-07-01 06:08 UTC, schlessera commented
@BrianHenryIE Now that I'm looking at the code again with fresh eyes... is there a reason why you're using closures in the first place? These two closures should rather be private methods of the class...

2022-07-01 06:13 UTC, BrianHenryIE commented
Not particularly. Probably because there's no PHPUnit tests leading me to need them be callable functions. 

Why `private` instead of `protected`? `static` still?

2022-08-31 15:52 UTC, danielbachhuber commented
Ship #61

2022-08-31 15:52 UTC, closed without merging